# Версия SwiftLint 0.34.0
# Не забывайте актуализировать документ https://virgo.ftc.ru/pages/viewpage.action?pageId=932152516 при изменении правил или обновлении версии SwiftLint.

excluded:
  - build
  - Pods
  - Carthage
  - BuildStuff
  - EdaSDK/EdaSDKTests
  - FTCFeeSDK
  - MockServer
  - fastlane

disabled_rules:
  - large_tuple
  - opening_brace
  - todo
  - vertical_parameter_alignment # выключено, так как swiftlint не умеет в табы
  - unused_setter_value # выключено, так как не оценена целесообразность

opt_in_rules:
  - anyobject_protocol
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_first_not_nil
  - convenience_type
  - empty_string
  - explicit_init
  - fatal_error_message
  - first_where
  - force_try
  - force_unwrapping
  - identical_operands
  - implicitly_unwrapped_optional
  - last_where
  - legacy_random
  - let_var_whitespace
  # - literal_expression_end_indentation # выключено, так как swiftlint не умеет в табы
  - lower_acl_than_parent
  - modifier_order
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - nimble_operator
  # - no_extension_access_modifier # пока не пришли к решению, что так лучше
  - operator_usage_whitespace
  - override_in_extension
  - overridden_super_call
  - prohibited_interface_builder
  - prohibited_super_call
  - redundant_nil_coalescing
  - redundant_type_annotation
  - sorted_first_last
  - static_operator
  - toggle_bool
  - trailing_closure
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - untyped_error_in_catch
  # - vertical_parameter_alignment_on_call # выключено, так как swiftlint не умеет в табы
  - vertical_whitespace_closing_braces
  - yoda_condition
  - strict_fileprivate

analyzer_rules:
  - explicit_self
  - unused_declaration

warning_threshold: 1

indentation: tabs

vertical_whitespace:
  max_empty_lines: 1

identifier_name:
  min_length: 2

statement_position:
  statement_mode: uncuddled_else

trailing_comma:
  mandatory_comma: true

cyclomatic_complexity:
  ignores_case_statements: true

trailing_closure:
  only_single_muted_parameter: true

modifier_order:
  preferred_modifier_order: [acl, override]

custom_rules:
  opening_brace_types:
    include: "*.swift"
    name: "Opening brace rule for types"
    message: "Opening brace should be on new line for type declarations"
    regex: '^[\t ]*(?:[@\w]+[\t ]+)*(?:class(?![\t ]+(?:func|var|let))|struct|protocol|extension|enum)[\t ]+(?:[^\n]+|[^\n]+\n{2,})\{\s*$'

  opening_brace_func:
    include: "*.swift"
    name: "Opening brace rule"
    message: "Opening brace should be on same line"
    match_kinds:
      - identifier
      - keyword
      - typeidentifier
    regex: '(?:init|func)[^{}]+(?:\s{2,}|[^ ])\{\s*$'

  opening_brace_statement:
    include: "*.swift"
    name: "Opening brace rule"
    message: "Opening brace should be on same line"
    match_kinds:
      - identifier
      - keyword
      - typeidentifier
    regex: '(?:if|guard|while|for|switch|do|else|catch)\s(?:\s{2,}|[^ ])\{\s*$'

  todo_fixme:
    include: "*.swift"
    name: "Todo and fixme"
    message: "Todo and fixme not exist task in Jira"
    regex: '\/\/\s*(?i:todo|fixme)(?i:(?!qis-\d+).)+$'

  explicit_failure_calls:
    include: "*.swift"
    name: "Avoid asserting 'false'"
    message: "Use assertionFailure(...) or preconditionFailure(...) instead"
    regex: '(assert|precondition)\(false\)|(assertion|precondition)(Failure\(\))'

  spacing_before_parenthesis:
    include: "*.swift"
    name: "Spacing before parenthesis rule"
    message: "There should be no space before opening parenthesis"
    match_kinds:
      - identifier
      - keyword
      - typeidentifier
    regex: '(?:init|func)[\w\s]+\s\('

  tabs_for_indentation:
    include: "*.swift"
    name: "Tabs for indentation rule"
    message: "Use tabs instead of spaces for indentation"
    regex: '^[\t ]*[ ]{4,}'

  prohibited_cyrillic:
    include: "*.swift"
    name: "Prohibited cyrillic rule"
    message: "Usage of cyrillic alphabet is prohibited (look for cyrillic С)"
    match_kinds:
      - identifier
      - typeidentifier
    regex: '[а-яА-ЯёЁ]'

  prohibited_global_constants:
    include: "*.swift"
    name: "Prohibited global constants rule"
    message: "Global constants are prohibited, make it private or use enum"
    regex: '^(?:(?:public|internal)\s+)?(?:let|var)\s+'

  explicit_false:
    include: "*.swift"
    name: "Explicit false rule"
    message: "Use `something == false` instead of `!something`"
    match_kinds:
      - identifier
      - keyword
    regex: '[\t ]+![a-zA-Z_]'

  comparison_assignment:
    include: "*.swift"
    name: "Discouraged usage of comparison assignment"
    message: "Wrap comparison expression with parenthesis"
    regex: '=[ \t]+[^(]\S+[ \t]+[=!]=[ \t]+\S+[^)]'
  
  required_final:
    include: "*.swift"
    name: "Required `final`"
    message: "Try to use composition over inheritance"
    regex: '^[\t ]*(?:(?:internal|private)[\t ]+)?class[\t ]+(?!(?:func|var|let)[\t ]+)'
